version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,info},{channel,info}]"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - sensor_network

  api-gateway:
    image: alonso02rupa/api-gateway
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      EXCHANGE_FOLDER: "exchange"
      SERVICES_FOLDER: "services"
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - sensor_network

  consumer_temperature:
    image: alonso02rupa/consumer-infrastructure:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      EXCHANGE_FOLDER: "exchange"
      SENSOR_NAME: "temperature"
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network
    volumes:
      - sensor_data:/app/sensor_data

  consumer_occupancy:
    image: alonso02rupa/consumer-infrastructure:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      EXCHANGE_FOLDER: "exchange"
      SENSOR_NAME: "occupancy"
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network
    volumes:
      - sensor_data:/app/sensor_data

  consumer_power:
    image: alonso02rupa/consumer-infrastructure:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      EXCHANGE_FOLDER: "exchange"
      SENSOR_NAME: "power_consumption"
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network
    volumes:
      - sensor_data:/app/sensor_data

  consumer_camera:
    image: alonso02rupa/consumer-infrastructure:latest
    environment:
      RABBITMQ_HOST: rabbitmq
      EXCHANGE_FOLDER: "exchange"
      SENSOR_NAME: "status"
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network
    volumes:
      - sensor_data:/app/sensor_data

networks:
  sensor_network:
    external: true

volumes:
  rabbitmq_data:
  sensor_data:
