version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,info},{channel,info}]"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Aumentado
          memory: 1G   # Aumentado
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - sensor_network

  api-gateway:
    image: alonso02rupa/api-gateway
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - sensor_network

  sensor_temperature:
    image: alonso02rupa/sensor-infrastructure:latest
    environment:
      SENSOR_TYPE: temperature
      TIME_SLEEP: 30
      API_GATEWAY_URL: http://api-gateway:8080/api/sensor-data
      SENSOR_CONFIG: '{"temperature": {"type": "float", "range": [18, 30]}, "humidity": {"type": "float", "range": [30, 80]}, "air_quality_index": {"type": "categorical", "values": ["low", "medium", "high"]}}'
    depends_on:
      api-gateway:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network

  sensor_occupancy:
    image: alonso02rupa/sensor-infrastructure:latest
    environment:
      SENSOR_TYPE: occupancy
      TIME_SLEEP: 30
      API_GATEWAY_URL: http://api-gateway:8080/api/sensor-data
      SENSOR_CONFIG: '{"occupancy": {"type": "int", "range": [0, 50]}, "movement": {"type": "categorical", "values": ["false", "true"]}, "location": {"type": "categorical", "values": ["zone1", "zone2", "zone3"]}, "dwell_time": {"type": "int", "range": [0, 60]}}'
    depends_on:
      api-gateway:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network

  sensor_power:
    image: alonso02rupa/sensor-infrastructure:latest
    environment:
      SENSOR_TYPE: power_consumption
      TIME_SLEEP: 5
      API_GATEWAY_URL: http://api-gateway:8080/api/sensor-data
      SENSOR_CONFIG: '{"power_consumption": {"type": "float", "range": [0, 10]}, "voltage": {"type": "float", "range": [220, 240]}, "current": {"type": "float", "range": [0, 20]}, "power_factor": {"type": "float", "range": [0, 1]}}'
    depends_on:
      api-gateway:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network

  sensor_camera:
    image: alonso02rupa/sensor-infrastructure:latest
    environment:
      SENSOR_TYPE: status
      TIME_SLEEP: 120
      API_GATEWAY_URL: http://api-gateway:8080/api/sensor-data
      SENSOR_CONFIG: '{"status": {"type": "categorical", "values": ["active", "inactive"]}, "alerts": {"type": "categorical", "values": ["motion detected", "unauthorized person", "abandoned object", "none"]}, "alert_level": {"type": "categorical", "values": ["low", "medium", "high"]}}'
    depends_on:
      api-gateway:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    networks:
      - sensor_network

networks:
  sensor_network:
    driver: bridge

volumes:
  rabbitmq_data:
